import Head from 'next/head'
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux'
import CoreLayout from '@/layouts/Core';
import Chat from '@/components/Chat';
import ChatLayoutMobile from '@/layouts/Chat';

export default function Home() {
  const router = useRouter()
  
  const loginStatus = useSelector(state => state.auth.loginStatus);
  const layout = useSelector(state => state.layoutSwitch.layout)

  useEffect(()=> {
    if(loginStatus) {
      alert("UE")
      router.push('/auth/login')
    }
  },[loginStatus , layout])
  return (
    <div className='overflow-hidden'>
      <Head>
        <title>Nexus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='hidden lg:block overflow-hidden'>
        <CoreLayout>
          <Chat />
        </CoreLayout>
      </div>
      <div className='block lg:hidden h-[calc(100vh-5rem)] overflow-hidden w-full'>
        {layout == 'core' ? <CoreLayout>
          <Chat />
        </CoreLayout> : layout == 'chat' && <div className='h-full'><ChatLayoutMobile /></div>}
      </div>
    </div>
  )
}
